---
title: "Final Grade Reflection"
author: "Fiona Norton"
format: pdf
editor: visual
theme: "simplex"
---

In this document, you make a data-based argument for the grade you've earned in this course. Your argument should include evidence from the supporting artifacts you've provided.

The output document should be a PDF or a Word Document, as it should be a **maximum** of 2-pages.

# Week 6 Grade Reflection

## Accomplishment of Learning Targets

Over the past six weeks I have strengthened my knowledge of R and R Studio through each preview activity, practice activity, lab assignment, and challenge problem. I have shown my proficiency in the majority of the learning targets and shown my desire to do better in areas that I do not feel as strong in. Beginning with the "Working With Data" learning targets, I can import data from a variety of formats which can be seen at the beginning of almost every assignment in the "setup" section, specifically in Practice Activity 4, Practice Activity 5.2, and Lab 3. I can select necessary columns from a dataset, filter rows from a dataframe, modify existing variables and create new variables in a dataframe for a variety of data types, as shown in Practice Activity 3, Practice Activity 5.1, and question 6 on Lab 3. I can use mutating joins to combine multiple dataframes and filtering joins to filter rows from a dataframe; this can be seen in Lab 4 questions 2, 5, and 6.

I am also proficient in data visualization and summarization, and I believe I have made a lot of progress in this area since my week 3 reflection. I can create visualizations for a variety of variable types, I use plot modifications to make my visualization clear to the reader, and I show creativity in my visualizations. All of these skills can be seen in my plots on recent labs, specifically Lab 4 questions 6 and 7, Lab 2 questions 9, 10, and 12, and almost all of Lab 5. I've shown that I can calculate numerical summaries of variables in Lab 4 question 6 and the "Familiar Words" section of Lab 3. I can find summaries of variables across multiple groups as I showed in Challenge 3 parts 2 and 3. I can create tables which make my summaries clear to the reader like in Lab 4 question 5 (finding top 5 regions), and Challenge 3 parts 2 and 3.

Finally I have shown proficiency in reproducibility and efficiency of my code. I have shown that I can create a reproducible analysis using RStudio projects, Quarto documents, and the here package at the beginning of each lab by importing the data with the "here" package and including the correct libraries. I can write well documented and tidy code which I try to always do but can be seen specifically in Lab 4 question 4. I can use iteration to reduce repetition in my code, like in Challenge 3 parts 2 and 3.

## Evidence of Continued Learning

### Extending My Thinking

Each week I show my willingness and ability to extend my thinking through the completion of challenge problems. In all of my challenge problems I dive deeper into a specific aspect of what we are learning that week and try to further my understanding of the topic. One example of this is the customization/challenge section of Lab 2 where I attempted to create and easier to read side by side box plot of the weights of different rodents by species including a color and label for the genus of that species as well as a customized color pallet. I am proficient in the learning targets discussed in the previous section because of the ways in which I am extending my thinking.

### Revising My Thinking

I am constantly revising my thinking by going back to old assignments and making improvements and working through preview activities multiple times to try to gain a better understanding of topics before coming to class. Each week I submit revisions to my labs and challenges based on the feedback provided by professor Theobold and my peers as well as the new knowledge I have gained in the time since the original submission. Along with these revisions, I write reflections about what I have learned from the changes and how I will use that knowledge moving forward. Good examples of how I have revised and extended my thinking include my Lab 3 and Lab 4 revision reflections. The revision process has helped me learn much more about R than I would have without receiving any feedback.

## Growth as a Team Member

### Collaborative Group Work

My growth as a team member throughout this course has mainly come as a result of our in class collaborative group work. Every Tuesday we work on a practice activity as a team. Our group has created an environment where everyone feels safe to ask questions and speak their minds. Our completion of these practice activities is a reflection of how well we are working together. Although we do not explicitly assign roles each week, there is a natural rotation of the roles depending on who is feeling strongest in the topic for that week. That person often emerges as the leader/captain for the week and the rest of us are happy to fall into other roles. I have realized that it can be difficult for me to ask questions when I feel behind because I do not want to hold back the group but I have come to understand the importance of working as a team and to realize that explaining things to other people is helpful for everyone's learning so it is always good to ask questions.

### Peer Code Review

I have completed each assigned peer code review carefully and with thought. I understand the importance of being kind to my peers but also realize that feedback is helpful so I try to give in depth reviews with words of encouragement. This can be seen in my peer reviews throughout the quarter.

## Attention to Personal Goals

At the beginning of this course I thought about my personal goals and decided to focus on improving my data visualization skills. I feel that I've made drastic progress in this area over the past 6 weeks and I hope to continue doing so. I have learned how to add colors and labels to a graph, how to create many different kinds of graphs with ggplot, how to customize a legend or exclude it all together, and how to graph only certain specific aspects of the data by combining the use of ggplot with dplyer functions. Additionally I wanted a general sense of "knowing R". Although this is very difficult to measure, I do feel like I am getting closer and closer each week.
