---
title: "Practice Activity 4: Tidy Data with tidyr"
execute:
  echo: true
  error: true 
author: "Fiona Norton"
format: 
  html: 
    code-fold: true
    code-summary: "Show code"
    theme: "materia"
editor: visual
---

## Data Import

```{r}
#| message: false
library(readxl) 
library(tidyverse)

military <- read_xlsx(here::here("datasets", 
                                 "gov_spending_per_capita.xlsx"), 
                      sheet = "Share of Govt. spending", 
                      skip = 6, 
                      n_max = 191)
```

## Data Cleaning

```{r}
military_clean <- military |> 
  mutate(across(.cols = everything(), ~na_if(., y = "xxx")), 
         across(.cols = everything(), ~na_if(., y = ". .")))
```

```{r}
military_clean <- military_clean |> 
  mutate(across(.cols = "1988":"2019", ~as.numeric(.)))
```

```{r}
cont_region <- read_xlsx(here::here("Week_4",
                                    "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

```{r}
military_clean <- military_clean |> 
  anti_join(cont_region, by = c("Country" = "Region"))
```

```{r}
military_long <- military_clean |> 
  pivot_longer(cols = "1988":"2019", names_to = "Year", values_to = "Spending")
```

```{r}
ggplot(data = military_long, 
       mapping = aes(y = Year, x = Spending) 
       ) + 
  geom_boxplot() 
```

```{r}
military_long |> 
  filter(Year == 1990) |> 
  slice_max(Spending)
```


